# Generated by Django 5.0.6 on 2024-07-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrojadizos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('Metal', 'Metal'), ('Madera', 'Madera'), ('PLA', 'PLA'), ('Goma Eva', 'Goma Eva'), ('Cerámica', 'Cerámica'), ('Cristal', 'Cristal'), ('Tejido', 'Tejido'), ('Espuma', 'Espuma')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True)),
            ],
            options={
                'verbose_name': 'Arrojadizo',
                'verbose_name_plural': 'Arrojadizos',
            },
        ),
        migrations.CreateModel(
            name='Banderines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('Metal', 'Metal'), ('Madera', 'Madera'), ('PLA', 'PLA'), ('Goma Eva', 'Goma Eva'), ('Cerámica', 'Cerámica'), ('Cristal', 'Cristal'), ('Tejido', 'Tejido'), ('Espuma', 'Espuma')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True)),
            ],
            options={
                'verbose_name': 'Banderin',
                'verbose_name_plural': 'Banderines',
            },
        ),
        migrations.CreateModel(
            name='Llaveros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('Metal', 'Metal'), ('Madera', 'Madera'), ('PLA', 'PLA'), ('Goma Eva', 'Goma Eva'), ('Cerámica', 'Cerámica'), ('Cristal', 'Cristal'), ('Tejido', 'Tejido'), ('Espuma', 'Espuma')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True)),
                ('sujeccion_llavero', models.CharField(blank=True, choices=[('Anilla', 'Anilla'), ('Cadena', 'Cadena'), ('Cierre de Plástico', 'Cierre de Plástico')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Llavero',
                'verbose_name_plural': 'Llaveros',
            },
        ),
        migrations.CreateModel(
            name='Medallas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('Metal', 'Metal'), ('Madera', 'Madera'), ('PLA', 'PLA'), ('Goma Eva', 'Goma Eva'), ('Cerámica', 'Cerámica'), ('Cristal', 'Cristal'), ('Tejido', 'Tejido'), ('Espuma', 'Espuma')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True)),
                ('sujeccion_medalla', models.CharField(blank=True, choices=[('Imperdible', 'Imperdible'), ('Imán', 'Imán')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Medalla',
                'verbose_name_plural': 'Medallas',
            },
        ),
        migrations.CreateModel(
            name='Medallon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('Metal', 'Metal'), ('Madera', 'Madera'), ('PLA', 'PLA'), ('Goma Eva', 'Goma Eva'), ('Cerámica', 'Cerámica'), ('Cristal', 'Cristal'), ('Tejido', 'Tejido'), ('Espuma', 'Espuma')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True)),
                ('sujeccion_medallon', models.CharField(blank=True, choices=[('Cadena', 'Cadena'), ('Cordón', 'Cordón'), ('Cuero', 'Cuero')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Medallon',
                'verbose_name_plural': 'Medallones',
            },
        ),
        migrations.CreateModel(
            name='ObjetoMagico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('Metal', 'Metal'), ('Madera', 'Madera'), ('PLA', 'PLA'), ('Goma Eva', 'Goma Eva'), ('Cerámica', 'Cerámica'), ('Cristal', 'Cristal'), ('Tejido', 'Tejido'), ('Espuma', 'Espuma')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True)),
            ],
            options={
                'verbose_name': 'Objeto Magico',
                'verbose_name_plural': 'Objetos Magicos',
            },
        ),
        migrations.CreateModel(
            name='Vajilla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('Cerámica', 'Cerámica'), ('Cristal', 'Cristal')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True)),
                ('volumen', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_taza', models.CharField(blank=True, choices=[('Tazas', 'Tazas'), ('Vasos de Chupito', 'Vasos de Chupito'), ('Jarra', 'Jarra'), ('Platos', 'Platos'), ('Vaso Vaquero', 'Vaso Vaquero')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Vajilla',
                'verbose_name_plural': 'Vajillas',
            },
        ),
    ]
