# Generated by Django 5.0.6 on 2024-06-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrojadizos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('Metal', 'Metal'), ('Madera', 'Madera'), ('PLA(3d)', 'PLA(3d)'), ('Goma Eva', 'Goma Eva'), ('Cerámica', 'Cerámica'), ('Cristal', 'Cristal'), ('Tejido', 'Tejido'), ('Espuma', 'Espuma')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='/static/imgs/no-image.png', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banderines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('Metal', 'Metal'), ('Madera', 'Madera'), ('PLA(3d)', 'PLA(3d)'), ('Goma Eva', 'Goma Eva'), ('Cerámica', 'Cerámica'), ('Cristal', 'Cristal'), ('Tejido', 'Tejido'), ('Espuma', 'Espuma')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='/static/imgs/no-image.png', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Llaveros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('Metal', 'Metal'), ('Madera', 'Madera'), ('PLA(3d)', 'PLA(3d)'), ('Goma Eva', 'Goma Eva'), ('Cerámica', 'Cerámica'), ('Cristal', 'Cristal'), ('Tejido', 'Tejido'), ('Espuma', 'Espuma')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='/static/imgs/no-image.png', null=True)),
                ('sujeccion_llavero', models.CharField(blank=True, choices=[('Anilla', 'Anilla'), ('Cadena', 'Cadena'), ('Cierre de Plástico', 'Cierre de Plástico')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medallas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('Metal', 'Metal'), ('Madera', 'Madera'), ('PLA(3d)', 'PLA(3d)'), ('Goma Eva', 'Goma Eva'), ('Cerámica', 'Cerámica'), ('Cristal', 'Cristal'), ('Tejido', 'Tejido'), ('Espuma', 'Espuma')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='/static/imgs/no-image.png', null=True)),
                ('sujeccion_medalla', models.CharField(blank=True, choices=[('Imperdible', 'Imperdible'), ('Imán', 'Imán')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medallon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('Metal', 'Metal'), ('Madera', 'Madera'), ('PLA(3d)', 'PLA(3d)'), ('Goma Eva', 'Goma Eva'), ('Cerámica', 'Cerámica'), ('Cristal', 'Cristal'), ('Tejido', 'Tejido'), ('Espuma', 'Espuma')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='/static/imgs/no-image.png', null=True)),
                ('sujeccion_medallon', models.CharField(blank=True, choices=[('Cadena', 'Cadena'), ('Cordón', 'Cordón'), ('Cuero', 'Cuero')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoMagico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('Metal', 'Metal'), ('Madera', 'Madera'), ('PLA(3d)', 'PLA(3d)'), ('Goma Eva', 'Goma Eva'), ('Cerámica', 'Cerámica'), ('Cristal', 'Cristal'), ('Tejido', 'Tejido'), ('Espuma', 'Espuma')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='/static/imgs/no-image.png', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vajilla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('Cerámica', 'Cerámica'), ('Cristal', 'Cristal')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='/static/imgs/no-image.png', null=True)),
                ('volumen', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_taza', models.CharField(blank=True, choices=[('Tazas', 'Tazas'), ('Vasos de Chupito', 'Vasos de Chupito'), ('Jarra', 'Jarra'), ('Platos', 'Platos'), ('Vaso Vaquero', 'Vaso Vaquero')], max_length=50, null=True)),
            ],
        ),
    ]
