# Generated by Django 5.0.6 on 2024-07-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrojadizos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('metal', 'Metal'), ('madera', 'Madera'), ('pla', 'PLA'), ('goma-eva', 'Goma Eva'), ('ceramica', 'Cerámica'), ('cristal', 'Cristal'), ('tejido', 'Tejido'), ('espuma', 'Espuma')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True)),
            ],
            options={
                'verbose_name': 'Arrojadizo',
                'verbose_name_plural': 'Arrojadizos',
            },
        ),
        migrations.CreateModel(
            name='Banderines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('metal', 'Metal'), ('madera', 'Madera'), ('pla', 'PLA'), ('goma-eva', 'Goma Eva'), ('ceramica', 'Cerámica'), ('cristal', 'Cristal'), ('tejido', 'Tejido'), ('espuma', 'Espuma')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True)),
            ],
            options={
                'verbose_name': 'Banderin',
                'verbose_name_plural': 'Banderines',
            },
        ),
        migrations.CreateModel(
            name='Llaveros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('metal', 'Metal'), ('madera', 'Madera'), ('pla', 'PLA'), ('goma-eva', 'Goma Eva'), ('ceramica', 'Cerámica'), ('cristal', 'Cristal'), ('tejido', 'Tejido'), ('espuma', 'Espuma')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True)),
                ('sujeccion_llavero', models.CharField(blank=True, choices=[('anilla', 'Anilla'), ('cadena', 'Cadena'), ('cierre-de-plastico', 'Cierre de Plástico')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Llavero',
                'verbose_name_plural': 'Llaveros',
            },
        ),
        migrations.CreateModel(
            name='Medallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('metal', 'Metal'), ('madera', 'Madera'), ('pla', 'PLA'), ('goma-eva', 'Goma Eva'), ('ceramica', 'Cerámica'), ('cristal', 'Cristal'), ('tejido', 'Tejido'), ('espuma', 'Espuma')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True)),
                ('sujeccion_medalla', models.CharField(blank=True, choices=[('imperdible', 'Imperdible'), ('iman', 'Imán')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Medalla',
                'verbose_name_plural': 'Medallas',
            },
        ),
        migrations.CreateModel(
            name='Medallon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('metal', 'Metal'), ('madera', 'Madera'), ('pla', 'PLA'), ('goma-eva', 'Goma Eva'), ('ceramica', 'Cerámica'), ('cristal', 'Cristal'), ('tejido', 'Tejido'), ('espuma', 'Espuma')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True)),
                ('sujeccion_medallon', models.CharField(blank=True, choices=[('cadena', 'Cadena'), ('cordon', 'Cordón'), ('cuero', 'Cuero')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Medallon',
                'verbose_name_plural': 'Medallones',
            },
        ),
        migrations.CreateModel(
            name='ObjetoMagico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('Metal', 'Metal'), ('Madera', 'Madera'), ('PLA', 'PLA'), ('Goma Eva', 'Goma Eva'), ('Cerámica', 'Cerámica'), ('Cristal', 'Cristal'), ('Tejido', 'Tejido'), ('Espuma', 'Espuma')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True)),
            ],
            options={
                'verbose_name': 'Objeto Magico',
                'verbose_name_plural': 'Objetos Magicos',
            },
        ),
        migrations.CreateModel(
            name='Vajilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, choices=[('metal', 'Metal'), ('madera', 'Madera'), ('pla', 'PLA'), ('goma-eva', 'Goma Eva'), ('ceramica', 'Cerámica'), ('cristal', 'Cristal'), ('tejido', 'Tejido'), ('espuma', 'Espuma')], max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True)),
                ('volumen', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_taza', models.CharField(blank=True, choices=[('tazas', 'Tazas'), ('vasos-de-chupito', 'Vasos de Chupito'), ('jarra', 'Jarra'), ('platos', 'Platos'), ('vaso-vaquero', 'Vaso Vaquero')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Vajilla',
                'verbose_name_plural': 'Vajillas',
            },
        ),
    ]
