# Generated by Django 5.0.6 on 2024-07-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrojadizos',
            options={'verbose_name': 'Arrojadizo', 'verbose_name_plural': 'Arrojadizos'},
        ),
        migrations.AlterModelOptions(
            name='banderines',
            options={'verbose_name': 'Banderin', 'verbose_name_plural': 'Banderines'},
        ),
        migrations.AlterModelOptions(
            name='llaveros',
            options={'verbose_name': 'Llavero', 'verbose_name_plural': 'Llaveros'},
        ),
        migrations.AlterModelOptions(
            name='medallas',
            options={'verbose_name': 'Medalla', 'verbose_name_plural': 'Medallas'},
        ),
        migrations.AlterModelOptions(
            name='medallon',
            options={'verbose_name': 'Medallon', 'verbose_name_plural': 'Medallones'},
        ),
        migrations.AlterModelOptions(
            name='objetomagico',
            options={'verbose_name': 'Objeto Magico', 'verbose_name_plural': 'Objetos Magicos'},
        ),
        migrations.AlterModelOptions(
            name='vajilla',
            options={'verbose_name': 'Vajilla', 'verbose_name_plural': 'Vajillas'},
        ),
        migrations.AlterField(
            model_name='arrojadizos',
            name='imagen_url',
            field=models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='banderines',
            name='imagen_url',
            field=models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='llaveros',
            name='imagen_url',
            field=models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='medallas',
            name='imagen_url',
            field=models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='medallon',
            name='imagen_url',
            field=models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='objetomagico',
            name='imagen_url',
            field=models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='vajilla',
            name='imagen_url',
            field=models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/error-500-page-empty-symbol-260nw-1711106146.jpg', null=True),
        ),
    ]
