# Generated by Django 5.0.6 on 2024-07-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrojadizos',
            name='material',
            field=models.CharField(blank=True, choices=[('metal', 'Metal'), ('madera', 'Madera'), ('pla', 'PLA'), ('goma-eva', 'Goma Eva'), ('ceramica', 'Cerámica'), ('cristal', 'Cristal'), ('tejido', 'Tejido'), ('espuma', 'Espuma')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='banderines',
            name='material',
            field=models.CharField(blank=True, choices=[('metal', 'Metal'), ('madera', 'Madera'), ('pla', 'PLA'), ('goma-eva', 'Goma Eva'), ('ceramica', 'Cerámica'), ('cristal', 'Cristal'), ('tejido', 'Tejido'), ('espuma', 'Espuma')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='llaveros',
            name='material',
            field=models.CharField(blank=True, choices=[('metal', 'Metal'), ('madera', 'Madera'), ('pla', 'PLA'), ('goma-eva', 'Goma Eva'), ('ceramica', 'Cerámica'), ('cristal', 'Cristal'), ('tejido', 'Tejido'), ('espuma', 'Espuma')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='llaveros',
            name='sujeccion_llavero',
            field=models.CharField(blank=True, choices=[('anilla', 'Anilla'), ('cadena', 'Cadena'), ('cierre-de-plastico', 'Cierre de Plástico')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medallas',
            name='material',
            field=models.CharField(blank=True, choices=[('metal', 'Metal'), ('madera', 'Madera'), ('pla', 'PLA'), ('goma-eva', 'Goma Eva'), ('ceramica', 'Cerámica'), ('cristal', 'Cristal'), ('tejido', 'Tejido'), ('espuma', 'Espuma')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medallas',
            name='sujeccion_medalla',
            field=models.CharField(blank=True, choices=[('imperdible', 'Imperdible'), ('iman', 'Imán')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medallon',
            name='material',
            field=models.CharField(blank=True, choices=[('metal', 'Metal'), ('madera', 'Madera'), ('pla', 'PLA'), ('goma-eva', 'Goma Eva'), ('ceramica', 'Cerámica'), ('cristal', 'Cristal'), ('tejido', 'Tejido'), ('espuma', 'Espuma')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medallon',
            name='sujeccion_medallon',
            field=models.CharField(blank=True, choices=[('cadena', 'Cadena'), ('cordon', 'Cordón'), ('cuero', 'Cuero')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vajilla',
            name='material',
            field=models.CharField(blank=True, choices=[('metal', 'Metal'), ('madera', 'Madera'), ('pla', 'PLA'), ('goma-eva', 'Goma Eva'), ('ceramica', 'Cerámica'), ('cristal', 'Cristal'), ('tejido', 'Tejido'), ('espuma', 'Espuma')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vajilla',
            name='tipo_taza',
            field=models.CharField(blank=True, choices=[('tazas', 'Tazas'), ('vasos-de-chupito', 'Vasos de Chupito'), ('jarra', 'Jarra'), ('platos', 'Platos'), ('vaso-vaquero', 'Vaso Vaquero')], max_length=50, null=True),
        ),
    ]
